<?php

return [
    'enforce_account_status' => env('SECURITY_ENFORCE_ACCOUNT_STATUS', true),
    'enforce_session_stamp' => env('SECURITY_ENFORCE_SESSION_STAMP', true),
    'enforce_email_verification' => env('SECURITY_ENFORCE_EMAIL_VERIFICATION', true),
    'enforce_username' => env('SECURITY_ENFORCE_USERNAME', true),
    'developer_bypass_validations' => env('SECURITY_DEVELOPER_BYPASS_VALIDATIONS', false),
    'developer_role' => env('SECURITY_DEVELOPER_ROLE', 'developer'),
    'superadmin_role' => env('SECURITY_SUPERADMIN_ROLE', 'super_admin'),
    'role_hierarchy' => [
        'developer' => 100,
        'super_admin' => 90,
        'admin' => 80,
        'manager' => 70,
        'user' => 10,
    ],
    'lockout_attempts' => (int) env('SECURITY_LOCKOUT_ATTEMPTS', 5),
    'lockout_minutes' => (int) env('SECURITY_LOCKOUT_MINUTES', 15),
    'password_history' => (int) env('SECURITY_PASSWORD_HISTORY', 5),
    'password_min_length' => (int) env('SECURITY_PASSWORD_MIN_LENGTH', 12),
    'password_require_mixed' => env('SECURITY_PASSWORD_REQUIRE_MIXED', true),
    'password_require_numbers' => env('SECURITY_PASSWORD_REQUIRE_NUMBERS', true),
    'password_require_symbols' => env('SECURITY_PASSWORD_REQUIRE_SYMBOLS', true),
    'password_require_uncompromised' => env('SECURITY_PASSWORD_REQUIRE_UNCOMPROMISED', true),
    'password_uncompromised_threshold' => (int) env('SECURITY_PASSWORD_UNCOMPROMISED_THRESHOLD', 0),
    'password_expiry_days' => (int) env('SECURITY_PASSWORD_EXPIRY_DAYS', 90),
    'password_expiry_notify_days' => (int) env('SECURITY_PASSWORD_EXPIRY_NOTIFY_DAYS', 7),
    'password_auto_reset_on_expiry' => env('SECURITY_PASSWORD_AUTO_RESET', true),
    'invitation_expires_days' => (int) env('SECURITY_INVITATION_EXPIRES_DAYS', 5),
    'threat_detection' => [
        'enabled' => env('SECURITY_THREAT_ENABLED', true),
        'aggressive' => env('SECURITY_THREAT_AGGRESSIVE', true),
        'cache_store' => env('SECURITY_THREAT_CACHE_STORE', 'rate_limit'),
        'risk_threshold' => (int) env('SECURITY_RISK_THRESHOLD', 8),
        'risk_decay_minutes' => (int) env('SECURITY_RISK_DECAY_MINUTES', 30),
        'burst_requests' => (int) env('SECURITY_BURST_REQUESTS', 90),
        'burst_window_seconds' => (int) env('SECURITY_BURST_WINDOW_SECONDS', 60),
        'admin_path_bonus' => (int) env('SECURITY_ADMIN_PATH_BONUS', 3),
        'auth_path_bonus' => (int) env('SECURITY_AUTH_PATH_BONUS', 3),
        'status_points' => [
            401 => 4,
            403 => 4,
            404 => 2,
            419 => 4,
            429 => 5,
            500 => 3,
            503 => 1,
        ],
        'suspicious_methods' => ['TRACE', 'TRACK', 'CONNECT'],
        'method_points' => (int) env('SECURITY_METHOD_POINTS', 6),
        'missing_user_agent_points' => (int) env('SECURITY_MISSING_UA_POINTS', 3),
        'short_user_agent_points' => (int) env('SECURITY_SHORT_UA_POINTS', 1),
        'user_agent_patterns' => [
            'scanner' => '/sqlmap|nikto|acunetix|burp|zap|nessus|masscan|nmap/i',
        ],
        'user_agent_pattern_points' => (int) env('SECURITY_UA_PATTERN_POINTS', 6),
        'max_forwarded_for' => (int) env('SECURITY_MAX_FORWARDED_FOR', 3),
        'forwarded_for_points' => (int) env('SECURITY_FORWARDED_FOR_POINTS', 2),
        'max_query_length' => (int) env('SECURITY_MAX_QUERY_LENGTH', 1600),
        'query_length_points' => (int) env('SECURITY_QUERY_LENGTH_POINTS', 2),
        'max_payload_kb' => (int) env('SECURITY_MAX_PAYLOAD_KB', 256),
        'payload_size_points' => (int) env('SECURITY_PAYLOAD_SIZE_POINTS', 3),
        'path_patterns' => [
            'path_traversal' => '/(\\.\\.\\/|\\.\\.\\\\|%2e%2e%2f|%2e%2e%5c)/i',
            'null_byte' => '/\\x00|%00/i',
        ],
        'path_pattern_points' => (int) env('SECURITY_PATH_PATTERN_POINTS', 5),
        'payload_patterns' => [
            'xss' => '/<script|onerror\\s*=|onload\\s*=|<iframe/i',
            'sql_injection' => '/\\b(select|union|insert|drop|sleep|benchmark)\\b/i',
            'command_injection' => '/(;|\\|\\||&&)\\s*(cat|ls|curl|wget|bash|sh)\\b/i',
        ],
        'payload_pattern_points' => (int) env('SECURITY_PAYLOAD_PATTERN_POINTS', 5),
        'auto_block' => env('SECURITY_AUTO_BLOCK', true),
        'user_block_minutes' => (int) env('SECURITY_USER_BLOCK_MINUTES', 90),
        'ip_block_minutes' => (int) env('SECURITY_IP_BLOCK_MINUTES', 45),
        'alert' => [
            'enabled' => env('SECURITY_ALERT_ENABLED', true),
            'log_channel' => env('SECURITY_ALERT_LOG_CHANNEL', 'security'),
            'emails' => array_values(array_filter(array_map('trim', explode(',', (string) env('SECURITY_ALERT_EMAILS', ''))))),
        ],
    ],
];
